# -*- coding: utf-8 -*-
# Generated by Django 2.2.9 on 2020-01-14 12:54

from django.db import migrations, models
import django.db.models.deletion
import djangocms_attributes_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLText',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_html_tags_htmltext', serialize=False, to='cms.CMSPlugin')),
                ('tag', models.CharField(choices=[('div', 'Division'), ('p', 'Paragraph'), ('h1', 'Heading 1'), ('h2', 'Heading 2'), ('h3', 'Heading 3'), ('h4', 'Heading 4'), ('h5', 'Heading 5'), ('h6', 'Heading 6'), ('form', 'Form'), ('button', 'Button'), ('input', 'Input')], default='div', max_length=50, verbose_name='HTML Tag')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Value')),
                ('attributes', djangocms_attributes_field.fields.AttributesField(blank=True, default=dict, verbose_name='Tag Attributes')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
